<?php

/**
 * csSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csSettingTable extends PlugincsSettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object csSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csSetting');
    }
}