<?php

/**
 * BaseDeviceLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $device_id
 * @property timestamp $time
 * @property text $description
 * @property Device $Device
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getDeviceId()    Returns the current record's "device_id" value
 * @method timestamp getTime()        Returns the current record's "time" value
 * @method text      getDescription() Returns the current record's "description" value
 * @method Device    getDevice()      Returns the current record's "Device" value
 * @method DeviceLog setId()          Sets the current record's "id" value
 * @method DeviceLog setDeviceId()    Sets the current record's "device_id" value
 * @method DeviceLog setTime()        Sets the current record's "time" value
 * @method DeviceLog setDescription() Sets the current record's "description" value
 * @method DeviceLog setDevice()      Sets the current record's "Device" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_log');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('device_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Device', array(
             'local' => 'device_id',
             'foreign' => 'id'));
    }
}