<?php

/**
 * BaseDevice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $config_id
 * @property Config $Config
 * @property Doctrine_Collection $Logs
 * @property Doctrine_Collection $Certificates
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getConfigId()     Returns the current record's "config_id" value
 * @method Config              getConfig()       Returns the current record's "Config" value
 * @method Doctrine_Collection getLogs()         Returns the current record's "Logs" collection
 * @method Doctrine_Collection getCertificates() Returns the current record's "Certificates" collection
 * @method Device              setId()           Sets the current record's "id" value
 * @method Device              setName()         Sets the current record's "name" value
 * @method Device              setConfigId()     Sets the current record's "config_id" value
 * @method Device              setConfig()       Sets the current record's "Config" value
 * @method Device              setLogs()         Sets the current record's "Logs" collection
 * @method Device              setCertificates() Sets the current record's "Certificates" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDevice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'minlength' => 5,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('config_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('cert_name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Config', array(
             'local' => 'config_id',
             'foreign' => 'id'));

        $this->hasMany('DeviceLog as Logs', array(
             'local' => 'id',
             'foreign' => 'device_id'));

        $this->hasMany('Mode3Certificate as Certificates', array(
             'local' => 'id',
             'foreign' => 'device_id'));
    }
}