<?php

/**
 * BaseDeviceConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property int $wireless_channel
 * @property enum $wireless_mode
 * @property string $update_server
 * @property Device $DeviceConfigs
 * @property Ssid $Ssids
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method int          getWirelessChannel()  Returns the current record's "wireless_channel" value
 * @method enum         getWirelessMode()     Returns the current record's "wireless_mode" value
 * @method string       getUpdateServer()     Returns the current record's "update_server" value
 * @method Device       getDeviceConfigs()    Returns the current record's "DeviceConfigs" value
 * @method Ssid         getSsids()            Returns the current record's "Ssids" value
 * @method DeviceConfig setId()               Sets the current record's "id" value
 * @method DeviceConfig setWirelessChannel()  Sets the current record's "wireless_channel" value
 * @method DeviceConfig setWirelessMode()     Sets the current record's "wireless_mode" value
 * @method DeviceConfig setUpdateServer()     Sets the current record's "update_server" value
 * @method DeviceConfig setDeviceConfigs()    Sets the current record's "DeviceConfigs" value
 * @method DeviceConfig setSsids()            Sets the current record's "Ssids" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_config');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('wireless_channel', 'int', 1, array(
             'type' => 'int',
             'unsigned' => true,
             'range' => 
             array(
              0 => 1,
              1 => 13,
             ),
             'length' => 1,
             ));
        $this->hasColumn('wireless_mode', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'b',
              1 => 'g',
              2 => 'n',
              3 => 'auto',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('update_server', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Device as DeviceConfigs', array(
             'local' => 'id',
             'foreign' => 'device_config_id'));

        $this->hasOne('Ssid as Ssids', array(
             'local' => 'id',
             'foreign' => 'device_config_id'));
    }
}