<?php

/**
 * BaseRadiusSsid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $retry_interval
 * @property string $own_ip
 * @property string $nas_identifier
 * @property string $radius_auth_ip
 * @property integer $radius_auth_port
 * @property string $radius_auth_shared_secret
 * @property string $radius_acct_ip
 * @property integer $radius_acct_port
 * @property string $radius_acct_shared_secret
 * @property integer $radius_acct_interim_interval
 * 
 * @method integer    getRetryInterval()                Returns the current record's "retry_interval" value
 * @method string     getOwnIp()                        Returns the current record's "own_ip" value
 * @method string     getNasIdentifier()                Returns the current record's "nas_identifier" value
 * @method string     getRadiusAuthIp()                 Returns the current record's "radius_auth_ip" value
 * @method integer    getRadiusAuthPort()               Returns the current record's "radius_auth_port" value
 * @method string     getRadiusAuthSharedSecret()       Returns the current record's "radius_auth_shared_secret" value
 * @method string     getRadiusAcctIp()                 Returns the current record's "radius_acct_ip" value
 * @method integer    getRadiusAcctPort()               Returns the current record's "radius_acct_port" value
 * @method string     getRadiusAcctSharedSecret()       Returns the current record's "radius_acct_shared_secret" value
 * @method integer    getRadiusAcctInterimInterval()    Returns the current record's "radius_acct_interim_interval" value
 * @method RadiusSsid setRetryInterval()                Sets the current record's "retry_interval" value
 * @method RadiusSsid setOwnIp()                        Sets the current record's "own_ip" value
 * @method RadiusSsid setNasIdentifier()                Sets the current record's "nas_identifier" value
 * @method RadiusSsid setRadiusAuthIp()                 Sets the current record's "radius_auth_ip" value
 * @method RadiusSsid setRadiusAuthPort()               Sets the current record's "radius_auth_port" value
 * @method RadiusSsid setRadiusAuthSharedSecret()       Sets the current record's "radius_auth_shared_secret" value
 * @method RadiusSsid setRadiusAcctIp()                 Sets the current record's "radius_acct_ip" value
 * @method RadiusSsid setRadiusAcctPort()               Sets the current record's "radius_acct_port" value
 * @method RadiusSsid setRadiusAcctSharedSecret()       Sets the current record's "radius_acct_shared_secret" value
 * @method RadiusSsid setRadiusAcctInterimInterval()    Sets the current record's "radius_acct_interim_interval" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRadiusSsid extends Ssid
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('radius_ssid');
        $this->hasColumn('retry_interval', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'default' => 600,
             'length' => 4,
             ));
        $this->hasColumn('own_ip', 'string', 15, array(
             'type' => 'string',
             'ip' => true,
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('nas_identifier', 'string', 48, array(
             'type' => 'string',
             'notnull' => true,
             'minlength' => 1,
             'length' => 48,
             ));
        $this->hasColumn('radius_auth_ip', 'string', 15, array(
             'type' => 'string',
             'ip' => true,
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('radius_auth_port', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'range' => 
             array(
              0 => 1,
              1 => 65535,
             ),
             'length' => 3,
             ));
        $this->hasColumn('radius_auth_shared_secret', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'minlength' => 1,
             'length' => 255,
             ));
        $this->hasColumn('radius_acct_ip', 'string', 15, array(
             'type' => 'string',
             'ip' => true,
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('radius_acct_port', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'range' => 
             array(
              0 => 1,
              1 => 65535,
             ),
             'length' => 3,
             ));
        $this->hasColumn('radius_acct_shared_secret', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'minlength' => 1,
             'length' => 255,
             ));
        $this->hasColumn('radius_acct_interim_interval', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'range' => 
             array(
              0 => 1,
             ),
             'default' => 600,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}