<?php

/**
 * BaseConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property int $wireless_channel
 * @property enum $wireless_mode
 * @property string $update_server
 * @property Doctrine_Collection $Devices
 * @property Doctrine_Collection $Ssids
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method int                 getWirelessChannel()  Returns the current record's "wireless_channel" value
 * @method enum                getWirelessMode()     Returns the current record's "wireless_mode" value
 * @method string              getUpdateServer()     Returns the current record's "update_server" value
 * @method Doctrine_Collection getDevices()          Returns the current record's "Devices" collection
 * @method Doctrine_Collection getSsids()            Returns the current record's "Ssids" collection
 * @method Config              setId()               Sets the current record's "id" value
 * @method Config              setWirelessChannel()  Sets the current record's "wireless_channel" value
 * @method Config              setWirelessMode()     Sets the current record's "wireless_mode" value
 * @method Config              setUpdateServer()     Sets the current record's "update_server" value
 * @method Config              setDevices()          Sets the current record's "Devices" collection
 * @method Config              setSsids()            Sets the current record's "Ssids" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('config');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('wireless_channel', 'int', 1, array(
             'type' => 'int',
             'unsigned' => true,
             'range' => 
             array(
              0 => 1,
              1 => 13,
             ),
             'length' => 1,
             ));
        $this->hasColumn('wireless_mode', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'b',
              1 => 'g',
              2 => 'n',
              3 => 'auto',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('update_server', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Device as Devices', array(
             'local' => 'id',
             'foreign' => 'config_id'));

        $this->hasMany('Ssid as Ssids', array(
             'local' => 'id',
             'foreign' => 'config_id'));
    }
}