generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Mode1
    theme:                 admin
    css:                   backend

    non_verbose_templates: true
    with_show:             false
    singular:              mode1
    plural:                mode1s
    route_prefix:          mode1
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   admin-gen   #setting the css to a placeholder

    config:
      actions:
        _new: { label: "Create a new Mode 1 SSID" }
      fields:  ~
      list:
        title: List of Mode 1 SSIDs
        display: [id, =name, _config, vlan, broadcast, group_rekey_interval, strict_rekey]
      filter:  ~
      form:    ~
      edit:
        title: Edit Mode 1 SSID
      new:
        title: Create Mode 1 SSID
