<?php

/**
 * DeviceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviceTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object DeviceTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Device');
    }

    public static function getFromName($name) {
        return Doctrine_Query::create()
            ->from('Device d')
            ->where('d.name = ?', $name)
            ->fetchOne();
    }

}