<?php

/**
 * DhcpServerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DhcpServerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DhcpServerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DhcpServer');
    }
}