<?php

/**
 * Mode1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mode1 extends BaseMode1 {

    public function  validate() {
        $errorStack = $this->getErrorStack();

        if ($this->wpa_mode != 'off') {
            if (strlen($this->passphrase) < 8) {
                $errorStack->add('passphrase', "Please supply a passphrase of 8 - 64 characters");
            }
            if (!$this->group_rekey_interval) {
                $errorStack->add('group_rekey_interval', "Please supply a group_rekey_interval");
            }
        }
    }

    public function __toString() {
        return $this->name;
    }

    public function preSave($event) {

        if ($this->passphrase == '') {
            $this->vpn_data_server = null;
        }
        if (!$this->group_rekey_interval) {
            $this->group_rekey_interval = null;
        }
    }
}