<?php

/**
 * Mode3Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mode3Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mode3Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mode3');
    }
}