<?php

/**
 * Mode3CertificateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mode3CertificateTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object Mode3CertificateTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Mode3Certificate');
    }
    
    public static function getFromMode3AndDevice($mode3, $device) {
        return Doctrine_Query::create()
            ->from('Mode3Certificate c')
            ->where('c.mode3_id = ?', is_object($mode3) ? $mode3->id : $mode3)
            ->andWhere('c.device_id = ?', is_object($device) ? $device->id : $device)
            ->fetchOne();
    }

}