<?php

/**
 * BaseDhcpServer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mode3_id
 * @property string $ip
 * @property Mode3 $Mode3
 * 
 * @method integer    getId()       Returns the current record's "id" value
 * @method integer    getMode3Id()  Returns the current record's "mode3_id" value
 * @method string     getIp()       Returns the current record's "ip" value
 * @method Mode3      getMode3()    Returns the current record's "Mode3" value
 * @method DhcpServer setId()       Sets the current record's "id" value
 * @method DhcpServer setMode3Id()  Sets the current record's "mode3_id" value
 * @method DhcpServer setIp()       Sets the current record's "ip" value
 * @method DhcpServer setMode3()    Sets the current record's "Mode3" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDhcpServer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dhcp_server');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('mode3_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ip', 'string', 15, array(
             'type' => 'string',
             'ip' => true,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mode3', array(
             'local' => 'mode3_id',
             'foreign' => 'id'));
    }
}