<?php

/**
 * BaseMode2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ssid_id
 * @property string $file_path
 * @property Ssid $Ssid
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getSsidId()    Returns the current record's "ssid_id" value
 * @method string  getFilePath()  Returns the current record's "file_path" value
 * @method Ssid    getSsid()      Returns the current record's "Ssid" value
 * @method Mode2   setId()        Sets the current record's "id" value
 * @method Mode2   setSsidId()    Sets the current record's "ssid_id" value
 * @method Mode2   setFilePath()  Sets the current record's "file_path" value
 * @method Mode2   setSsid()      Sets the current record's "Ssid" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMode2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mode2');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('ssid_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'minlength' => 4,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ssid', array(
             'local' => 'ssid_id',
             'foreign' => 'id'));
    }
}