<?php

/**
 * BaseMode3Certificate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mode3_id
 * @property integer $device_id
 * @property string $public_key
 * @property string $private_key
 * @property string $cert_of_authority
 * @property Mode3 $Mode3
 * @property Device $Device
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method integer          getMode3Id()           Returns the current record's "mode3_id" value
 * @method integer          getDeviceId()          Returns the current record's "device_id" value
 * @method string           getPublicKey()         Returns the current record's "public_key" value
 * @method string           getPrivateKey()        Returns the current record's "private_key" value
 * @method string           getCertOfAuthority()   Returns the current record's "cert_of_authority" value
 * @method Mode3            getMode3()             Returns the current record's "Mode3" value
 * @method Device           getDevice()            Returns the current record's "Device" value
 * @method Mode3Certificate setId()                Sets the current record's "id" value
 * @method Mode3Certificate setMode3Id()           Sets the current record's "mode3_id" value
 * @method Mode3Certificate setDeviceId()          Sets the current record's "device_id" value
 * @method Mode3Certificate setPublicKey()         Sets the current record's "public_key" value
 * @method Mode3Certificate setPrivateKey()        Sets the current record's "private_key" value
 * @method Mode3Certificate setCertOfAuthority()   Sets the current record's "cert_of_authority" value
 * @method Mode3Certificate setMode3()             Sets the current record's "Mode3" value
 * @method Mode3Certificate setDevice()            Sets the current record's "Device" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMode3Certificate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mode3_certificate');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('mode3_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('device_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('public_key', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('private_key', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('cert_of_authority', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mode3', array(
             'local' => 'mode3_id',
             'foreign' => 'id'));

        $this->hasOne('Device', array(
             'local' => 'device_id',
             'foreign' => 'id'));
    }
}