<?php

/**
 * BaseSsid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $vlan
 * @property boolean $broadcast
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getName()      Returns the current record's "name" value
 * @method integer getVlan()      Returns the current record's "vlan" value
 * @method boolean getBroadcast() Returns the current record's "broadcast" value
 * @method Ssid    setId()        Sets the current record's "id" value
 * @method Ssid    setName()      Sets the current record's "name" value
 * @method Ssid    setVlan()      Sets the current record's "vlan" value
 * @method Ssid    setBroadcast() Sets the current record's "broadcast" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSsid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ssid');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'minlength' => 1,
             'nospace' => true,
             'regexp' => '/^[a-zA-Z0-9_]+$/',
             'length' => 32,
             ));
        $this->hasColumn('vlan', 'integer', 2, array(
             'type' => 'integer',
             'range' => 
             array(
              0 => 1,
              1 => 4096,
             ),
             'length' => 2,
             ));
        $this->hasColumn('broadcast', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}