<?php

/**
 * BaseMode1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $config_id
 * @property enum $wpa_mode
 * @property string $passphrase
 * @property integer $group_rekey_interval
 * @property boolean $strict_rekey
 * @property Config $Config
 * 
 * @method integer getConfigId()             Returns the current record's "config_id" value
 * @method enum    getWpaMode()              Returns the current record's "wpa_mode" value
 * @method string  getPassphrase()           Returns the current record's "passphrase" value
 * @method integer getGroupRekeyInterval()   Returns the current record's "group_rekey_interval" value
 * @method boolean getStrictRekey()          Returns the current record's "strict_rekey" value
 * @method Config  getConfig()               Returns the current record's "Config" value
 * @method Mode1   setConfigId()             Sets the current record's "config_id" value
 * @method Mode1   setWpaMode()              Sets the current record's "wpa_mode" value
 * @method Mode1   setPassphrase()           Sets the current record's "passphrase" value
 * @method Mode1   setGroupRekeyInterval()   Sets the current record's "group_rekey_interval" value
 * @method Mode1   setStrictRekey()          Sets the current record's "strict_rekey" value
 * @method Mode1   setConfig()               Sets the current record's "Config" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseMode1 extends Ssid
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('mode1');
        $this->hasColumn('config_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('wpa_mode', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'wpa',
              1 => 'wpa2',
              2 => 'off',
             ),
             'default' => 'wpa2',
             'notnull' => true,
             ));
        $this->hasColumn('passphrase', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('group_rekey_interval', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 600,
             'length' => 4,
             ));
        $this->hasColumn('strict_rekey', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Config', array(
             'local' => 'config_id',
             'foreign' => 'id'));
    }
}