<?php

/**
 * BaseMode2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $config_id
 * @property string $file_name
 * @property Config $Config
 * 
 * @method integer getConfigId()  Returns the current record's "config_id" value
 * @method string  getFileName()  Returns the current record's "file_name" value
 * @method Config  getConfig()    Returns the current record's "Config" value
 * @method Mode2   setConfigId()  Sets the current record's "config_id" value
 * @method Mode2   setFileName()  Sets the current record's "file_name" value
 * @method Mode2   setConfig()    Sets the current record's "Config" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMode2 extends RadiusSsid
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('mode2');
        $this->hasColumn('config_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('file_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'minlength' => 4,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Config', array(
             'local' => 'config_id',
             'foreign' => 'id'));
    }
}