generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Config
    theme:                 admin
    css:                   backend

    non_verbose_templates: true
    with_show:             false
    singular:              config
    plural:                configs
    route_prefix:          config
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   admin-gen

    config:
      actions:
        _new: { label: "Create a new configuration" }
      fields:  ~
      list:
        title: List of Configs
        display: [id, =name, update_server, wireless_channel, wireless_mode, _mode1s, _mode2s, _mode3s]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
