#!/bin/sh
#
#   HostAPD starting script renovated default
#   FreeBSD rc script so we have multiple instances

# PROVIDE: openvpn_bridges
# REQUIRE: netif
# BEFORE: openvpn

. /etc/rc.subr

name="openvpn_bridges"
rcvar=`set_rcvar`
start_cmd="${name}_start"
stop_cmd=":"

load_rc_config $name

eval "${rcvar}=\${${rcvar}:-'NO'}"

openvpn_bridges_start() {
    echo "Starting OpenVPN bridges"

    count=${ovpn_mode3_bridge_count:-0}

    i=0
    while [ $i -le $((count-1)) ]
    do
        bridge_var="ovpn_mode3_bridge${i}_bridge"
        eval "bridge=\$$bridge_var"
        tap_var="ovpn_mode3_bridge${i}_tap"
        eval "tap=\$$tap_var"
        wlan_var="ovpn_mode3_bridge${i}_wlan"
        eval "wlan=\$$wlan_var"

        echo "Starting bridge $bridge"

        # openvpn --mktun --dev $t
        # ifconfig_bridge1="addm wlan0 addm tap0 up"

        # openvpn --mktun --dev $tap
        ifconfig $tap create
        ifconfig $bridge create
        ifconfig $bridge addm $wlan addm $tap up

        i=$((i+1))
    done

}
run_rc_command "$1"