all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=cugar
      username: root
      password: ~
    
      attributes:
         use_native_enum: true
         use_dql_callbacks: true
