generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DhcpServer
    theme:                 admin
    css:                   backend

    non_verbose_templates: true
    with_show:             false
    singular:              dhcpserver
    plural:                dhcpservers
    route_prefix:          dhcp_server
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   admin-gen   #setting the css to a placeholder

    config:
      actions:
        _new: { label: "Create a new mode 3 DHCP server" }
      fields:  ~
      list:
        display: [id, _mode3, ip]
        title: Mode 3 DHCP servers
      filter:  ~
      form:    ~
      edit:
        title: Edit mode 3 DHCP server
      new:
        title: Create mode 3 DHCP server
