<?php

/**
 * DeviceLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviceLogTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object DeviceLogTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('DeviceLog');
    }

    public static function addLog($device, $time, $descr) {

        $log = new DeviceLog();
        $log->device_id = is_object($device) ? $device->id : $device;
        $log->time = $time;
        $log->description = $desc;
        $log->save();

        return $log;
    }
}