<?php

/**
 * DeviceConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviceConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeviceConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeviceConfig');
    }
}