<?php

/**
 * Mode3CertificateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mode3CertificateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mode3CertificateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mode3Certificate');
    }
}