<?php

/**
 * Mode1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mode1Table extends SsidTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mode1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mode1');
    }
}