<?php

/**
 * Mode2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mode2Table extends SsidTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mode2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mode2');
    }
}