<?php

/**
 * RadiusSsidTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadiusSsidTable extends SsidTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadiusSsidTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RadiusSsid');
    }
}