<?php

/**
 * SsidTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SsidTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SsidTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ssid');
    }
}