all:
  certificate_dir: /home/cugar/keys


  sf_admin_dash:
    web_dir: /sfAdminDashPlugin
    image_dir: /sfAdminDashPlugin/images/icons/
    default_image: config.png
    resize_mode: thumbnail
    site: CUGAR Server admin
    include_path: true
    include_jquery_no_conflict: false
    logout: true
    login_route: '@sf_guard_signin'
    logout_route: '@sf_guard_signout'

    categories:
      Configs:
        items:
          Configs:
            url: config
      SSIDs:
        items:
          Mode 1:
            url: mode1
          Mode 2:
            url: mode2
          Mode 3:
            url: mode3
      Mode 3:
        items:
          DHCP servers:
            url: dhcp_server
          Device certificates:
            url: mode3_certificate
      Device Management:
        items:
          Devices:
            url: device
      User Management:
        items:
          Users:
            url: sf_guard_user
          Groups:
            url: sf_guard_group
          Permissions:
            url: sf_guard_permission

