#!/bin/sh
#		HostAPD starting script renovated default
#		FreeBSD rc script so we have multiple instances

for file in `ls /etc/ | grep openvpn`
do
        echo "$file configuration exists"
        /usr/sbin/openvpn --config "/etc/$file/$file.conf" --daemon
done