generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Ssid
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ssid
    plural:                ssids
    route_prefix:          ssid
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder

    config:
      actions:
        _new: { label: "Create a new SSID" }
      fields:  ~
      list:
        title: List of SSIDs
        display: [id, =name, mode, vlan, broadcast, wpa_mode]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
